name: Deploy

on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:
      - "**" # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github
          use-cache: "true"

      - name: cURL
        id: curl
        run: |
          response=$(curl --silent --output /dev/null --header 'Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}' --write-out "%{http_code}" ${{ vars.COOLIFY_WEBHOOK }}); echo "response=$response" >> $GITHUB_OUTPUT

      - name: Updating summary
        run: |
          echo "### Coolify response: ${{ steps.code.outputs.response }}" >> $GITHUB_STEP_SUMMARY
